-- 砂石设备监测数据表
CREATE TABLE IF NOT EXISTS `sand_equipment_monitor` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `device_id` INT(11) DEFAULT NULL COMMENT '设备地址/设备ID',
  `node` INT(11) DEFAULT NULL COMMENT '节点',
  `pm2` FLOAT DEFAULT NULL COMMENT 'PM2.5 (ug/m³)',
  `pm10` FLOAT DEFAULT NULL COMMENT 'PM10 (ug/m³)',
  `tsp` FLOAT DEFAULT NULL COMMENT '总悬浮颗粒物 (ug/m³)',
  `noise` FLOAT DEFAULT NULL COMMENT '噪声 (dB)',
  `temperature` FLOAT DEFAULT NULL COMMENT '温度',
  `humidity` FLOAT DEFAULT NULL COMMENT '湿度',
  `wind_power` FLOAT DEFAULT NULL COMMENT '风力 (m/s)',
  `wind_speed` FLOAT DEFAULT NULL COMMENT '风速 (m/s)',
  `wind_direct` FLOAT DEFAULT NULL COMMENT '风向(方位数值)',
  `wind_direct_degrees` FLOAT DEFAULT NULL COMMENT '风向(角度)',
  `lng` FLOAT DEFAULT NULL COMMENT '经度',
  `lat` FLOAT DEFAULT NULL COMMENT '纬度',
  `coordinate_type` INT(11) DEFAULT NULL COMMENT '坐标类型：0-百度经纬度,1-联通基站,2-移动基站,3-GPS',
  `relay_status` VARCHAR(50) DEFAULT NULL COMMENT '继电器状态',
  `create_time` DATETIME DEFAULT NULL COMMENT '数据采集时间',
  `device_name` VARCHAR(100) DEFAULT NULL COMMENT '设备名称',
  `position` VARCHAR(200) DEFAULT NULL COMMENT '设备位置',
  `wind_dir` VARCHAR(50) DEFAULT NULL COMMENT '风向(中文描述)',
  `sync_time` DATETIME DEFAULT NULL COMMENT '数据同步时间',
  PRIMARY KEY (`id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_sync_time` (`sync_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='砂石设备监测数据表';
